/* ============================================================
   PathFinder — shared data: RIASEC traits, quiz questions,
   and the college course catalog used by both the quiz and
   the course explorer.
   ============================================================ */

/* ---------- RIASEC trait reference ---------- */
const TRAITS = {
  R: { name: "Realistic",     tag: "Hands-On Doer",   desc: "You like working with your hands, tools, machines, or the outdoors, and you prefer practical, concrete tasks over theory." },
  I: { name: "Investigative", tag: "Curious Thinker",  desc: "You enjoy analyzing, researching, and solving complex problems. You like asking “why” and “how” before jumping in." },
  A: { name: "Artistic",      tag: "Creative Soul",    desc: "You value self-expression, originality, and imagination. You like creating things and thinking outside the box." },
  S: { name: "Social",        tag: "People Helper",    desc: "You enjoy helping, teaching, or caring for others, and you thrive in cooperative, people-centered settings." },
  E: { name: "Enterprising",  tag: "Natural Leader",   desc: "You like leading, persuading, and taking initiative. You're drawn to goals, competition, and influencing outcomes." },
  C: { name: "Conventional",  tag: "Organized Planner",desc: "You like structure, accuracy, and clear processes. You're comfortable with data, details, and organizing information." },
};

const TRAIT_ORDER = ["R", "I", "A", "S", "E", "C"];

/* ---------- Quiz questions ----------
   Each question is a statement the student rates 1-5 (agree scale).
   `trait` = which RIASEC dimension it feeds. Two questions per trait,
   mixing interests, skills, and personality framing. */
const QUIZ_QUESTIONS = [
  { id: 1,  trait: "R", text: "Given the choice, I'd rather build, fix, or take something apart with my hands than sit and read about how it works." },
  { id: 2,  trait: "R", text: "I feel most productive and focused when I'm doing something physical or hands-on, instead of just planning or discussing it." },
  { id: 3,  trait: "I", text: "When something doesn't make sense, I like digging into the problem, gathering information, and figuring out exactly why it happens." },
  { id: 4,  trait: "I", text: "I'm the person in the group who keeps asking “what if” and “how does that actually work” until I fully understand something." },
  { id: 5,  trait: "A", text: "I enjoy expressing myself creatively — through writing, art, music, design, or performance — more than most people I know." },
  { id: 6,  trait: "A", text: "Given a task, I'd rather come up with my own original approach than just follow the standard method step by step." },
  { id: 7,  trait: "S", text: "I feel genuinely energized after spending time helping a friend, classmate, or even a stranger work through a problem." },
  { id: 8,  trait: "S", text: "People often come to me first when they need advice, comfort, or someone to explain something clearly." },
  { id: 9,  trait: "E", text: "In group projects, I naturally end up taking charge, setting the direction, and pushing the team toward the goal." },
  { id: 10, trait: "E", text: "I enjoy convincing others, pitching new ideas, or negotiating my way toward a better outcome, even when it's a challenge." },
  { id: 11, trait: "C", text: "I like keeping things organized and predictable — clear schedules, tidy files, budgets, or a solid step-by-step plan." },
  { id: 12, trait: "C", text: "I'm comfortable spending long stretches of time working carefully and accurately with numbers, records, or detailed rules." },
];

const LIKERT = [
  { value: 1, label: "Not me at all" },
  { value: 2, label: "A little like me" },
  { value: 3, label: "Somewhat like me" },
  { value: 4, label: "A lot like me" },
  { value: 5, label: "Totally me" },
];

/* ---------- Icon set (inline SVG strings, no external assets) ---------- */
const ICONS = {
  code: '<path d="M9 18l-6-6 6-6M15 6l6 6-6 6"/>',
  heart: '<path d="M12 21s-7.5-4.7-10-9.3C.3 8.2 2 4.5 5.7 4A5.3 5.3 0 0112 7.3 5.3 5.3 0 0118.3 4C22 4.5 23.7 8.2 22 11.7 19.5 16.3 12 21 12 21z"/>',
  briefcase: '<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 012-2h4a2 2 0 012 2v2M3 12h18"/>',
  building: '<rect x="4" y="3" width="16" height="18" rx="1"/><path d="M9 8h1M14 8h1M9 12h1M14 12h1M9 16h1M14 16h1"/>',
  calc: '<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M8 6h8M8 10h.01M12 10h.01M16 10h.01M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01M16 18h.01"/>',
  hammer: '<path d="M14.5 4.5l5 5L17 12l-5-5 2.5-2.5zM3 21l7-7M12.5 8.5L9 12l3 3 3.5-3.5"/>',
  bolt: '<path d="M13 2L3 14h7l-1 8 10-12h-7l1-8z"/>',
  compass: '<circle cx="12" cy="12" r="10"/><path d="M16 8l-2.5 6-6 2.5 2.5-6z"/>',
  book: '<path d="M4 4.5A2.5 2.5 0 016.5 2H20v17H6.5A2.5 2.5 0 004 16.5v-12z"/><path d="M4 16.5A2.5 2.5 0 016.5 19H20"/>',
  shield: '<path d="M12 2l8 4v6c0 5-3.5 8-8 10-4.5-2-8-5-8-10V6l8-4z"/>',
  globe: '<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15 15 0 010 20 15 15 0 010-20z"/>',
  leaf: '<path d="M11 20A7 7 0 014 13c0-6 5-11 16-11 0 11-5 16-11 16-1.5 0-2.7-.3-4-1z"/><path d="M4 20l7-7"/>',
  flask: '<path d="M9 2v6L3.5 18a2 2 0 001.8 3h13.4a2 2 0 001.8-3L15 8V2M9 2h6"/>',
  palette: '<circle cx="12" cy="12" r="10"/><circle cx="8" cy="11" r="1.2"/><circle cx="12" cy="8" r="1.2"/><circle cx="16" cy="11" r="1.2"/><circle cx="10" cy="15" r="1.2"/><path d="M12 22c-1 0-1.5-.7-1.5-1.5S11 19 12 19a2.5 2.5 0 000-5H9"/>',
  scale: '<path d="M12 3v18M5 7l-3 6a3 3 0 006 0l-3-6zM19 7l-3 6a3 3 0 006 0l-3-6zM5 7h14M8 21h8"/>',
  camera: '<path d="M4 8h3l2-3h6l2 3h3v11H4z"/><circle cx="12" cy="13.5" r="3.5"/>',
  users: '<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20a6.5 6.5 0 0113 0M16 9a3 3 0 110-6M14.5 13.5a6.5 6.5 0 015.5 6.4"/>',
  sprout: '<path d="M12 21V10M12 10C12 6 9 4 5 4c0 4 2 7 7 6zM12 10c0-3.5 2.5-6 6-6 0 4-2 6.5-6 6z"/>',
  wrench: '<path d="M14.7 6.3a4 4 0 00-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 005.4-5.4l-2.8 2.8-2-2z"/>',
  search: '<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>',
  target: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
  spark: '<path d="M12 3l1.8 5.4L19 10l-5.2 1.6L12 17l-1.8-5.4L5 10l5.2-1.6L12 3z"/>',
};

function icon(name, cls) {
  const body = ICONS[name] || ICONS.spark;
  return `<svg class="icon ${cls || ""}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
}

/* ---------- Course catalog ----------
   riasec: relative weights (0-3) per RIASEC dimension, used for
   quiz matching via cosine similarity. */
const COURSES = [
  {
    id: "cs",
    name: "BS Computer Science",
    field: "Technology",
    icon: "code",
    riasec: { R: 1, I: 3, A: 1, S: 0, E: 1, C: 2 },
    blurb: "For people who like building things from scratch and solving puzzles — whether you want to code apps, design websites, or fix broken systems.",
    about: "Computer Science focuses on the theory and practice of computing — algorithms, data structures, programming languages, and how computers actually solve problems under the hood. You'll spend a lot of time writing and debugging code, but also learning the math and logic that explains why that code works. Early years usually cover programming fundamentals and discrete math; later years let you specialize in areas like artificial intelligence, cybersecurity, mobile development, or data science. It's a great fit if you like breaking big problems into smaller logical steps and don't mind a fair amount of trial and error before things click.",
    careers: ["Software Engineer", "Data Scientist", "AI/ML Engineer", "Systems Analyst", "Game Developer"],
    skills: ["Logical thinking", "Problem-solving", "Programming", "Math & algorithms", "Attention to detail"],
    subjects: ["Mathematics", "Programming", "Physics", "Statistics", "Computer Systems"],
  },
  {
    id: "it",
    name: "BS Information Technology",
    field: "Technology",
    icon: "wrench",
    riasec: { R: 2, I: 2, A: 0, S: 1, E: 1, C: 2 },
    blurb: "For people who'd rather keep the tech world actually running — setting up networks, untangling IT headaches, and being the one who fixes it when something breaks.",
    about: "Information Technology is the applied, hands-on side of computing — setting up networks, managing servers, securing data, and supporting the tech that organizations rely on every day. Compared to Computer Science, IT leans less on heavy theory and more on getting real systems installed, configured, and running reliably. You'll work with operating systems, databases, and networks directly, often troubleshooting problems under time pressure. It suits students who like practical, tangible tech work — the kind where you can see and fix something right away — over long stretches of abstract programming.",
    careers: ["Network Administrator", "IT Support Specialist", "Cybersecurity Analyst", "Cloud Engineer", "Web Developer"],
    skills: ["Troubleshooting", "Networking", "System setup", "Customer support", "Practical problem-solving"],
    subjects: ["Networking", "Programming", "Database Systems", "Hardware", "Cybersecurity"],
  },
  {
    id: "nursing",
    name: "BS Nursing",
    field: "Health Sciences",
    icon: "heart",
    riasec: { R: 1, I: 2, A: 0, S: 3, E: 1, C: 1 },
    blurb: "For people who want a career built around showing up for others — staying calm, capable, and present when someone needs help the most.",
    about: "Nursing trains you to assess, care for, and advocate for patients — combining medical knowledge with hands-on care, empathy, and quick decision-making in clinical settings. Coursework blends science subjects like anatomy and pharmacology with supervised clinical duty in hospitals and community health settings, so you're applying what you learn on real patients fairly early on. It's a physically and emotionally demanding path — long shifts, high-stakes situations, and constant contact with people who are unwell or afraid. In return, it offers steady demand, clear licensure requirements, and one of the most direct ways to make a visible difference in someone's life.",
    careers: ["Registered Nurse", "Clinical Educator", "Nurse Manager", "Public Health Nurse", "ICU Nurse"],
    skills: ["Empathy", "Attention to detail", "Composure under pressure", "Communication", "Clinical judgment"],
    subjects: ["Anatomy & Physiology", "Biology", "Chemistry", "Pharmacology", "Community Health"],
  },
  {
    id: "medtech",
    name: "BS Medical Technology",
    field: "Health Sciences",
    icon: "flask",
    riasec: { R: 1, I: 3, A: 0, S: 1, E: 0, C: 2 },
    blurb: "For people who love science but would rather work quietly behind the scenes — running the tests that help doctors figure out what's actually going on.",
    about: "Medical Technology (Medical Laboratory Science) is about analyzing blood, tissue, and other samples in a lab to help diagnose disease. It's precise, methodical, science-driven work behind the scenes of healthcare — you rarely interact with patients directly, but doctors depend on your results to make treatment decisions. Expect heavy coursework in chemistry, microbiology, and hematology, plus training on lab equipment and strict safety and quality protocols. It's a strong choice if you love biology and chemistry but would rather work carefully at a bench than in a fast-paced ward.",
    careers: ["Medical Technologist", "Lab Supervisor", "Pathology Assistant", "Research Technician", "Blood Bank Specialist"],
    skills: ["Precision", "Scientific analysis", "Focus", "Lab techniques", "Following protocols"],
    subjects: ["Biology", "Chemistry", "Microbiology", "Hematology", "Clinical Chemistry"],
  },
  {
    id: "psych",
    name: "BS Psychology",
    field: "Social Sciences",
    icon: "users",
    riasec: { R: 0, I: 3, A: 1, S: 3, E: 0, C: 0 },
    blurb: "For people who are always trying to figure out why others act the way they do — and want to turn that curiosity into a way to actually help people.",
    about: "Psychology explores how people think, feel, and behave, from childhood development to motivation, memory, and mental health. You'll study mental processes, development, and behavior through both theory and hands-on research methods like surveys, experiments, and statistics. It's a flexible degree — some graduates go on to counseling, HR, or social work, while others pursue graduate school to become licensed psychologists or researchers. Good for students who are naturally curious about why people act the way they do and enjoy both people-focused work and data-driven research.",
    careers: ["Guidance Counselor", "HR Specialist", "Research Assistant", "Behavioral Therapist*", "UX Researcher"],
    skills: ["Active listening", "Empathy", "Research methods", "Critical thinking", "Communication"],
    subjects: ["General Psychology", "Statistics", "Human Development", "Abnormal Psychology", "Research Methods"],
  },
  {
    id: "biz",
    name: "BS Business Administration",
    field: "Business",
    icon: "briefcase",
    riasec: { R: 0, I: 1, A: 0, S: 1, E: 3, C: 2 },
    blurb: "For people who like the idea of running things — whether that's a team, a project, or eventually a business of your own.",
    about: "Business Administration gives you a broad toolkit for running and growing organizations — covering marketing, finance, operations, human resources, and leadership so you can work in or start almost any kind of company. It's less specialized than a degree like Accountancy, which makes it flexible: you can lean toward a track that fits you, whether that's marketing, entrepreneurship, or management. Group projects, case studies, and presentations are common, since much of the work is about making decisions and convincing others they're right. A natural fit if you're interested in how companies work and like the idea of leading teams or launching your own venture someday.",
    careers: ["Marketing Manager", "Business Analyst", "Entrepreneur", "Operations Manager", "Sales Executive"],
    skills: ["Leadership", "Communication", "Strategic thinking", "Negotiation", "Financial literacy"],
    subjects: ["Marketing", "Management", "Economics", "Accounting Basics", "Business Law"],
  },
  {
    id: "acct",
    name: "BS Accountancy",
    field: "Business",
    icon: "calc",
    riasec: { R: 0, I: 1, A: 0, S: 0, E: 1, C: 3 },
    blurb: "For people who feel weirdly satisfied when the numbers finally balance — and don't mind being the one everyone trusts to keep things accurate.",
    about: "Accountancy trains you to record, analyze, and report financial information accurately, following a strict set of standards and regulations. It's detail-heavy and rule-based — you'll work extensively with numbers, spreadsheets, and financial statements, and accuracy matters far more than creativity here. The program is structured around eventually taking the CPA licensure exam, which opens doors in auditing, taxation, and corporate finance. Well suited to students who are comfortable with math, enjoy order and precision, and don't mind detailed, rules-driven work.",
    careers: ["Certified Public Accountant", "Auditor", "Tax Consultant", "Financial Analyst", "Controller"],
    skills: ["Attention to detail", "Numerical accuracy", "Organization", "Ethics & integrity", "Analytical thinking"],
    subjects: ["Financial Accounting", "Taxation", "Auditing", "Business Law", "Cost Accounting"],
  },
  {
    id: "civeng",
    name: "BS Civil Engineering",
    field: "Engineering",
    icon: "building",
    riasec: { R: 3, I: 2, A: 0, S: 0, E: 1, C: 1 },
    blurb: "For people who want their work to still be standing in fifty years — designing the roads, bridges, and buildings people actually use every day.",
    about: "Civil Engineering combines math, physics, and hands-on design to plan and build infrastructure like roads, bridges, buildings, and water systems that communities depend on every day. You'll learn to calculate structural loads, analyze materials, and design systems that have to work safely for decades, often visiting active construction sites as part of your training. The coursework is heavy on calculus and physics early on, shifting toward specialized design and project management later. Good for students who enjoy solving concrete, real-world problems and like seeing their work exist as something physical you can walk past.",
    careers: ["Civil Engineer", "Structural Engineer", "Construction Manager", "Urban Planner", "Site Engineer"],
    skills: ["Math & physics", "Spatial reasoning", "Project planning", "Technical drawing", "Problem-solving"],
    subjects: ["Calculus", "Physics", "Structural Design", "Surveying", "Construction Materials"],
  },
  {
    id: "eleceng",
    name: "BS Electrical Engineering",
    field: "Engineering",
    icon: "bolt",
    riasec: { R: 3, I: 3, A: 0, S: 0, E: 0, C: 1 },
    blurb: "For people who are fascinated by how power and electronics actually work — and want to be the one designing the systems behind them.",
    about: "Electrical Engineering is about generating, controlling, and applying electrical power and electronics — from power grids and motors to microchips and control systems. Expect a heavy load of math and physics, especially circuit analysis, electromagnetics, and signal processing, alongside lab work building and testing real circuits. It splits into paths like power systems, electronics, or telecommunications as you advance, so there's room to specialize toward what interests you most. Best suited to students who enjoy analytical, technical problem-solving and are comfortable with abstract math applied to physical systems.",
    careers: ["Electrical Engineer", "Power Systems Engineer", "Controls Engineer", "Electronics Designer", "Field Engineer"],
    skills: ["Analytical thinking", "Math & physics", "Circuit design", "Troubleshooting", "Precision"],
    subjects: ["Circuit Analysis", "Calculus", "Physics", "Electronics", "Power Systems"],
  },
  {
    id: "mecheng",
    name: "BS Mechanical Engineering",
    field: "Engineering",
    icon: "hammer",
    riasec: { R: 3, I: 2, A: 0, S: 0, E: 1, C: 1 },
    blurb: "For people who can't resist taking things apart to see how they work — and want to design the machines that make everyday life run.",
    about: "Mechanical Engineering covers the design, building, and maintenance of machines and mechanical systems — engines, HVAC, robotics, manufacturing equipment, and more. It's one of the broadest engineering fields, blending physics, thermodynamics, and materials science with hands-on design using CAD software and prototyping. You'll often work in teams building and testing physical models, not just running calculations on paper. A strong fit if you like taking things apart to understand how they work and want a versatile engineering degree that opens doors across manufacturing, automotive, energy, and robotics industries.",
    careers: ["Mechanical Engineer", "Design Engineer", "Manufacturing Engineer", "Robotics Engineer", "Maintenance Engineer"],
    skills: ["Hands-on building", "Math & physics", "CAD design", "Problem-solving", "Mechanical reasoning"],
    subjects: ["Thermodynamics", "Calculus", "Physics", "Machine Design", "Materials Science"],
  },
  {
    id: "arch",
    name: "BS Architecture",
    field: "Design",
    icon: "compass",
    riasec: { R: 2, I: 1, A: 3, S: 0, E: 1, C: 1 },
    blurb: "For people who notice how a space makes them feel — and want to design buildings that are both functional and genuinely beautiful.",
    about: "Architecture blends art and engineering — you'll design buildings and spaces that are functional, safe, and beautiful, balancing creative vision with technical construction knowledge. Studio classes are the core of the program: long hours sketching, modeling, and defending design decisions in front of critics, alongside more technical courses in structures and building systems. It demands both imagination and discipline, since a design also has to follow codes, budgets, and real-world constraints. Ideal for students who are creative but also detail-oriented, and who enjoy thinking about how spaces affect the people who use them.",
    careers: ["Architect", "Urban Designer", "Interior Designer", "Design Consultant", "Project Coordinator"],
    skills: ["Creativity", "Spatial reasoning", "Technical drawing", "Design software", "Attention to detail"],
    subjects: ["Design Studio", "Architectural History", "Structural Concepts", "Math", "Building Technology"],
  },
  {
    id: "multimedia",
    name: "BA Multimedia Arts",
    field: "Design",
    icon: "palette",
    riasec: { R: 0, I: 0, A: 3, S: 1, E: 1, C: 0 },
    blurb: "For people who are always making something — videos, art, designs — and want a career built around their creative eye.",
    about: "Multimedia Arts is a creative, hands-on program covering graphic design, animation, video production, and digital storytelling — ideal if you love making things look and feel great. You'll build a portfolio through constant project work, learning industry software for illustration, motion graphics, and editing while developing your own visual style along the way. Feedback and revision are a big part of the process, so it helps to take criticism well and iterate quickly. Great for students who are naturally drawn to visual creativity and want a career where their output is something people can actually see and share.",
    careers: ["Graphic Designer", "Animator", "Video Editor", "UI/UX Designer", "Content Creator"],
    skills: ["Visual creativity", "Design software", "Storytelling", "Attention to aesthetics", "Adaptability"],
    subjects: ["Design Fundamentals", "Animation", "Digital Illustration", "Video Production", "Typography"],
  },
  {
    id: "comm",
    name: "BA Communication",
    field: "Media & Arts",
    icon: "camera",
    riasec: { R: 0, I: 1, A: 2, S: 2, E: 2, C: 0 },
    blurb: "For people who are natural storytellers — the ones who always know how to explain, write, or say things in a way that actually lands.",
    about: "Communication covers journalism, media production, and public relations — teaching you to research, write, and tell stories that inform, persuade, or entertain across platforms. Coursework mixes writing-heavy classes with practical media production, so you might be filing a news story one week and producing a short video or podcast the next. It also touches on media ethics and how information spreads, which matters more than ever in a world of social media and misinformation. A good fit for students who are strong communicators, curious about current events, and enjoy shaping how a message reaches an audience.",
    careers: ["Journalist", "Content Strategist", "PR Specialist", "Broadcaster", "Social Media Manager"],
    skills: ["Writing", "Storytelling", "Research", "Public speaking", "Media production"],
    subjects: ["Journalism", "Media Writing", "Public Relations", "Broadcasting", "Media Ethics"],
  },
  {
    id: "edu",
    name: "BS Education",
    field: "Education",
    icon: "book",
    riasec: { R: 0, I: 1, A: 1, S: 3, E: 1, C: 1 },
    blurb: "For people who love explaining things until it finally clicks for someone else — and want to spend a career doing exactly that.",
    about: "Education prepares you to teach — covering subject mastery, lesson planning, classroom management, and child or adolescent development so you can guide students effectively. You'll typically choose a specialization, like early childhood, elementary, or a specific secondary subject, and complete supervised teaching practice in real classrooms before graduating. It's as much about patience and communication as it is about content knowledge, since explaining an idea clearly to a room of learners is its own skill. Well suited to students who enjoy mentoring others and find real satisfaction in watching someone else understand something for the first time.",
    careers: ["Classroom Teacher", "Curriculum Developer", "School Administrator", "Instructional Designer", "Tutor"],
    skills: ["Communication", "Patience", "Lesson planning", "Classroom management", "Empathy"],
    subjects: ["Educational Psychology", "Curriculum Design", "Child Development", "Teaching Methods", "Subject Specialization"],
  },
  {
    id: "crim",
    name: "BS Criminology",
    field: "Public Service",
    icon: "shield",
    riasec: { R: 2, I: 1, A: 0, S: 2, E: 1, C: 1 },
    blurb: "For people who are drawn to solving mysteries and keeping others safe — and want a hands-on career in law enforcement or justice.",
    about: "Criminology examines crime, its causes, and the justice system, preparing you for careers in law enforcement, forensics, investigation, or corrections. You'll study criminal law and procedure alongside sociology and psychology, trying to understand not just what happened in a crime but why. Physical fitness training and coursework in forensic science and investigation techniques are common, since many graduates go on to take police or law enforcement entrance exams. Suited to students who care about justice and public safety, can stay level-headed under pressure, and are comfortable with structure and discipline.",
    careers: ["Police Officer", "Forensic Investigator", "Crime Analyst", "Correctional Officer", "Security Consultant"],
    skills: ["Observation", "Physical fitness", "Critical thinking", "Integrity", "Composure under pressure"],
    subjects: ["Criminal Law", "Forensic Science", "Criminal Justice", "Sociology", "Investigation Techniques"],
  },
  {
    id: "polsci",
    name: "BA Political Science",
    field: "Social Sciences",
    icon: "scale",
    riasec: { R: 0, I: 2, A: 0, S: 2, E: 2, C: 1 },
    blurb: "For people who can't help debating current events — and want to actually understand how power, law, and government really work.",
    about: "Political Science examines government systems, policy, and law, looking at how power is gained, used, and challenged both locally and internationally. It's a reading- and writing-heavy program, built around research papers, debate, and analyzing arguments from multiple sides of an issue. Many students treat it as a pre-law track, but it also leads directly into public administration, diplomacy, and policy work. A strong choice for students who enjoy following current events, arguing a position with evidence, and thinking critically about how societies are governed.",
    careers: ["Lawyer*", "Policy Analyst", "Diplomat", "Legislative Staffer", "Public Administrator"],
    skills: ["Critical thinking", "Debate & persuasion", "Research & writing", "Analysis", "Civic knowledge"],
    subjects: ["Political Theory", "Public Administration", "International Relations", "Law", "Research Methods"],
  },
  {
    id: "tourism",
    name: "BS Tourism Management",
    field: "Hospitality",
    icon: "globe",
    riasec: { R: 1, I: 0, A: 1, S: 3, E: 2, C: 0 },
    blurb: "For people who light up talking about travel — and want a career built around planning experiences people will actually remember.",
    about: "Tourism Management prepares you to plan, market, and manage travel experiences — from tour operations to destination marketing — with a strong focus on customer service. You'll study geography, marketing, and the operations behind travel and destinations, often alongside language and cultural training that helps when working with international guests. Internships with airlines, tour operators, or travel agencies are common and give you real exposure to the pace of the industry. A good fit if you're outgoing, enjoy learning about different places and cultures, and like the idea of a career that involves constant contact with new people.",
    careers: ["Tour Operator", "Travel Consultant", "Event Coordinator", "Destination Marketer", "Airline Staff"],
    skills: ["Customer service", "Organization", "Cultural awareness", "Communication", "Adaptability"],
    subjects: ["Tourism Planning", "Marketing", "Geography", "Event Management", "Hospitality Operations"],
  },
  {
    id: "hrm",
    name: "BS Hospitality Management",
    field: "Hospitality",
    icon: "users",
    riasec: { R: 1, I: 0, A: 1, S: 3, E: 2, C: 0 },
    blurb: "For people who genuinely enjoy taking care of others — and want a fast-paced career running hotels, restaurants, or events.",
    about: "Hospitality Management trains you to run hotels, restaurants, and events — blending customer service, operations, and business skills in a fast-paced, people-first industry. Programs usually include hands-on training kitchens, front-desk and housekeeping operations, and food and beverage service, so you learn the business from the ground up rather than just in theory. On-the-job internships in hotels or restaurants are a core part of most curricula. Well suited to students who thrive under pressure, genuinely enjoy taking care of people, and don't mind irregular hours in exchange for a dynamic, service-driven career.",
    careers: ["Hotel Manager", "Restaurant Manager", "Chef*", "Event Planner", "Guest Services Manager"],
    skills: ["Customer service", "Multitasking", "Leadership", "Composure under pressure", "Organization"],
    subjects: ["Food & Beverage Ops", "Hotel Operations", "Culinary Basics", "Event Management", "Business Basics"],
  },
  {
    id: "agri",
    name: "BS Agriculture",
    field: "Agriculture & Science",
    icon: "sprout",
    riasec: { R: 3, I: 2, A: 0, S: 1, E: 0, C: 0 },
    blurb: "For people who'd rather be outside than stuck in a classroom — and care about where food actually comes from.",
    about: "Agriculture combines biology and hands-on fieldwork to improve crop and livestock production, sustainability, and food systems — great for students who love science and the outdoors. You'll study soil science, plant and animal biology, and increasingly the business side of farming, since modern agriculture is as much about managing an operation as growing crops. Fieldwork and lab work go hand in hand, often on a school farm or in partnership with local agribusinesses. A strong option for students who enjoy applied science, don't mind outdoor and physical work, and care about food security or sustainability.",
    careers: ["Agriculturist", "Agribusiness Manager", "Agricultural Researcher", "Farm Manager", "Extension Officer"],
    skills: ["Practical science", "Problem-solving", "Outdoor work", "Data collection", "Sustainability mindset"],
    subjects: ["Crop Science", "Soil Science", "Animal Science", "Biology", "Agribusiness"],
  },
  {
    id: "bio",
    name: "BS Biology",
    field: "Natural Sciences",
    icon: "leaf",
    riasec: { R: 1, I: 3, A: 0, S: 1, E: 0, C: 1 },
    blurb: "For people who ask \"but why\" about literally everything alive — and want a science foundation that can lead almost anywhere, from medicine to research.",
    about: "Biology is the study of living organisms — from the molecular level to entire ecosystems — covering genetics, cell biology, ecology, and physiology along the way. Lab work is a constant throughout the program, teaching you to design experiments, use scientific equipment, and analyze real data rather than just memorize facts. It's a flexible science degree that serves as a springboard into medicine, research, biotechnology, environmental work, or teaching. Ideal for naturally curious students who enjoy asking how living things work and are comfortable with a heavy science and math course load.",
    careers: ["Research Scientist", "Lab Technician", "Environmental Consultant", "Science Educator", "Pre-Med Track"],
    skills: ["Scientific inquiry", "Analysis", "Lab work", "Attention to detail", "Curiosity"],
    subjects: ["Cell Biology", "Genetics", "Ecology", "Chemistry", "Microbiology"],
  },
];
